import { auth } from "@/lib/firebase/firebaseConfig";
import { getSalesforceAuthURL } from "@/lib/salesforce/clientAuthorization";
import { useRouter } from "next/navigation";
import { useAuth } from "./auth/AuthProvider";
import { signOut } from "@/lib/firebase/clientAuthentication";

export default function AdminPage() {
  const router = useRouter();
  const auth = useAuth();

  const generateNewRefreshToken = () => {
    const url = getSalesforceAuthURL();
    url.searchParams.set(
      "state",
      JSON.stringify({ idToken: auth.token?.token })
    );
    router.push(url.toString());
  };

  return (
    <div className="flex flex-col items-center w-full text-black">
      <h3>
        The only function of the admin account on this website is to regenerate
        a refresh token for Salesforce. The refresh token is what allows this
        application to access the Salesforce database. If, for some reason, it
        expires and becomes outdated, nothing on this website will work for any
        LPF client. It must be manually regenerated by clicking the button
        below.
      </h3>
      <button
        className="w-2/3 m-4 bg-teal text-white rounded-lg"
        onClick={generateNewRefreshToken}
      >
        Generate New Refresh Token
      </button>
      <button className="w-2/3 bg-teal text-white rounded-lg" onClick={signOut}>
        Log Out
      </button>
    </div>
  );
}
